name: uwurandom
description: A random string generator of nonsense. Like /dev/urandom but basically better.
version: 1.0.0
repository: https://github.com/Rapougnac/uwurandom.git

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  dart_code_metrics: ^5.7.6
  lints: ^2.0.0
  test: ^1.16.0
